"""adicionar itens no pedido

Revision ID: 745482b8664c
Revises: b6a420fba419
Create Date: 2026-02-05 17:31:29.743073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '745482b8664c'
down_revision: Union[str, Sequence[str], None] = 'b6a420fba419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'itens_pedidos', 'pedidos', ['pedido'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'users', ['usuario'], ['id'])
    op.alter_column('users', 'senha',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'senha',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               existing_nullable=False)
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
    # ### end Alembic commands ###
